import { usePreferencesStore } from '@/lib/stores/preferences-store';
import type { ProxyService } from '@/lib/types';

// control-plane's GlobalExceptionFilter (src/errors/exception.filter.ts) formats
// structured errors as `{statusCode, errorCode, message, error: {code, message}}`
// with a top-level `errorCode` — `error.code` carries the same value, nested, as a
// fallback. Most call sites' bodies aren't JSON at all (plain text, an upstream's
// own error page), so a parse failure is expected, not exceptional — never let it
// mask the original HTTP error by throwing here.
function parseErrorCode(body: string): string | undefined {
  if (!body) return undefined;
  try {
    const parsed = JSON.parse(body) as { errorCode?: unknown; error?: { code?: unknown } };
    if (typeof parsed.errorCode === 'string') return parsed.errorCode;
    if (typeof parsed.error?.code === 'string') return parsed.error.code;
    return undefined;
  } catch {
    return undefined;
  }
}

export class ApiError extends Error {
  readonly status: number;
  readonly service: ProxyService;
  readonly path: string;
  /**
   * Structured upstream error code, when the body carried one.
   *
   * **Not control-plane-exclusive.** The top-level `errorCode` is the control
   * plane's (SCREAMING_SNAKE — `CONTEXT_ID_MISMATCH`,
   * `FEDERATION_UPSTREAM_RATE_LIMITED`), but the nested `error.code` fallback
   * above also matches the registry's own RFC-ACDP-0007 §5 wire envelope
   * (`acdp-registry-types/src/error.rs:83-92`), so a direct registry call
   * populates this with lowercase snake_case (`schema_violation`,
   * `rate_limited`, `not_authorized`). The two vocabularies do not collide
   * today, but nothing enforces that — so anything keyed by this value must
   * match exactly and must not infer provenance from the code alone. See
   * `lib/utils/api-error-messages.ts`.
   */
  readonly errorCode?: string;

  /**
   * The raw response text, verbatim — including `''` when the upstream sent
   * nothing.
   *
   * `message` is NOT a faithful carrier of this: the constructor falls back to
   * `Request failed with status ${status}` for an empty body, so a caller that
   * parsed `message` would be handing prose to `JSON.parse`. Callers that want
   * structured data out of a failure response (`pingHealth` reads the version
   * off a degraded `/healthz`) need the bytes, not the display string.
   *
   * Deliberately a raw string rather than an eagerly-parsed `bodyJson`:
   * `parseErrorCode` already parses this same text for its own purpose, and
   * most error bodies in this app are not JSON at all, so a second eager parse
   * would pay a cost on every error everywhere to serve one caller. Parsing
   * stays with the caller that wants it.
   */
  readonly body: string;

  /**
   * Whether these bytes actually came from the upstream service, or were
   * generated by this console before the request ever left the box.
   *
   * NOT inferable from `status`. The proxy route mints its own 400/403/502,
   * `middleware.ts` its own 401/403/503, and Next returns a 500 when the route
   * handler throws (an unset `*_BASE_URL` out of `getIntegrationConfig`) — so
   * a console-side 401 ("sign in at /login required") looks identical to an
   * upstream 401 if all you have is the number. The proxy stamps
   * `x-acdp-ui-proxy` with the service it forwarded to, on the pass-through
   * path ONLY (`app/api/proxy/[service]/[...path]/route.ts`), so a stamp
   * matching the service this call asked about is a fact rather than a guess.
   *
   * What it cannot tell you: whether the *service* answered or some
   * intermediary between the proxy and the service did (a reverse proxy's own
   * 504 is passed through and stamped). It answers "did this come from beyond
   * our own boundary", which is the honest limit of what the console knows.
   */
  readonly fromUpstream: boolean;

  constructor(status: number, body: string, service: ProxyService, path: string, fromUpstream = false) {
    super(body || `Request failed with status ${status}`);
    this.name = 'ApiError';
    this.status = status;
    this.service = service;
    this.path = path;
    this.body = body;
    this.fromUpstream = fromUpstream;
    this.errorCode = parseErrorCode(body);
  }

  get isNotFound() {
    return this.status === 404;
  }
}

export function proxyUrl(service: ProxyService, path: string): string {
  return `/api/proxy/${service}${path.startsWith('/') ? path : `/${path}`}`;
}

/**
 * Did these bytes cross our own boundary — for the service we asked for?
 *
 * The proxy route sets `x-acdp-ui-proxy` immediately before re-streaming an
 * upstream response and on no other path, so every envelope this console mints
 * itself — the route's 400/403/502, `middleware.ts`'s 401, 503 and
 * Origin-mismatch 403, and Next's 500 for an unset `*_BASE_URL` — arrives
 * without it. `proxy-route.test.ts` guards both directions: the stamp present
 * on pass-through, and absent on the route's own 403 and both 502 envelopes.
 *
 * The VALUE is compared, not just the presence: the route writes the service
 * it forwarded to, so `=== service` additionally rules out a response that
 * crossed the boundary towards a DIFFERENT upstream than the caller asked
 * about (a same-origin relative redirect landing a `registry-a` call on
 * `registry-b`'s answer, say). `degraded`, and the version beside it, are
 * claims about one named service; a stamp from another service is no evidence
 * for them.
 */
function cameFromUpstream(response: Response, service: ProxyService): boolean {
  return response.headers.get('x-acdp-ui-proxy') === service;
}

/**
 * Warned at most once per page load — see `warnOnUnstampedSuccess` below for
 * why the condition is worth detecting at all. Health is polled every 15s
 * across four services (`connection-status.tsx:13`, `health-checks.tsx:20`;
 * the 30s figure this comment used to give is `use-dashboard.ts:12`, a
 * different query) and the condition is a deployment-wide property, so one
 * line is the whole signal and a hundred would bury it. (The sibling warning in
 * `middleware.ts` deliberately goes the other way, per-request: that one lands
 * in a server log an operator may attach to late, this one in a browser console
 * they are already looking at.)
 */
let warnedUnstampedSuccess = false;

/**
 * An unstamped 2xx from `/api/proxy/*` is impossible in a correct deployment —
 * so seeing one is evidence, not noise.
 *
 * The failure path reads the stamp because "no console envelope carries a
 * version" is a fact about today's code rather than an enforced invariant.
 * "No console path emits a 2xx for `/api/proxy/*`" is equally unenforced, and
 * reading the stamp here costs one header lookup while detecting two things
 * nothing else in the repo can see:
 *
 *  - an intermediary (CDN, corporate proxy, ingress) stripping unknown `x-*`
 *    response headers, which silently flips every genuine `degraded` to
 *    `unreachable` across all four health surfaces;
 *  - a redirect the BROWSER followed off this boundary — an intermediary in
 *    front of the console bouncing `/api/proxy/*` elsewhere (or the route's own
 *    3xx guard regressing), after which the response inspected here is the
 *    target's and carries no stamp of ours. The route no longer relays a 3xx
 *    itself, so this arm is about the hop the proxy cannot see, not that one.
 *
 * Deliberately a warning and not a throw: this is a detection signal, and a
 * console that refused to render because a header went missing would trade a
 * cosmetic wrongness for a total outage. `scripts/smoke-routes.mjs` cannot do
 * this job — it checks page routes only and holds no session cookie, so it
 * meets middleware's unstamped 401 by design.
 */
function warnOnUnstampedSuccess(response: Response, service: ProxyService, path: string): void {
  if (warnedUnstampedSuccess || cameFromUpstream(response, service)) return;
  warnedUnstampedSuccess = true;
  const stamp = response.headers.get('x-acdp-ui-proxy');
  console.warn(
    `[ACDP UI] ${response.status} from /api/proxy/${service}${path} without this console's own provenance stamp ` +
      `(x-acdp-ui-proxy: ${stamp === null ? 'absent' : `'${stamp}'`}, expected '${service}'). ` +
      'The proxy stamps every response it relays, so something between it and this browser is rewriting ' +
      'response headers, or the response never went through it. Health words (degraded vs unreachable) and the ' +
      '"live" version markers will under-report until that is fixed. Warned once per page load.',
  );
}

// The proxy/stream gate (middleware.ts) returns 401 when the operator
// session is missing/invalid. Demo mode never reaches this: lib/api/client.ts
// returns mock data before touching fetchJson/fetchText, so this only fires
// in real mode.
//
// This runs outside any component (fetchJson/fetchText are plain module
// functions, often called from React Query's queryFn), so there's no
// `useRouter()` to reach for — a full navigation via `location.assign` is
// the correct tool here, not a lint smell.
//
// `fromUpstream` is the whole point of the second parameter. Two very
// different things answer 401 at this boundary:
//
//  - middleware.ts:94, when the operator's session cookie is missing or
//    expired. That 401 is console-minted and carries no stamp, and signing in
//    again genuinely fixes it. This is the case the redirect exists for.
//  - a real upstream, relayed through the proxy WITH the stamp — typically a
//    wrong or rotated CONTROL_PLANE_API_KEY. The operator's own session is
//    perfectly valid, so bouncing them to /login sends them to re-enter a
//    passphrase that was never the problem; signing in returns them to the
//    page, which 401s again. A loop that signing in cannot break.
//
// The gate lives inside this function rather than at the call sites (which is
// what #91 proposed) so the whole redirect policy stays in one place: "which
// 401s" is part of that policy, not the caller's business, and there are two
// call sites today that would each have to remember the guard.
function redirectToLoginOn401(status: number, fromUpstream: boolean): void {
  if (status !== 401 || fromUpstream || typeof window === 'undefined') return;
  if (window.location.pathname === '/login') return;
  // eslint-disable-next-line @next/next/no-location-assign-relative-destination
  window.location.assign('/login');
}

export async function fetchJson<T>(service: ProxyService, path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(proxyUrl(service, path), {
    ...init,
    headers: { 'content-type': 'application/json', ...(init?.headers ?? {}) },
    cache: 'no-store',
  });

  if (!response.ok) {
    const message = await response.text().catch(() => '');
    // Computed once and shared: the redirect decision and the thrown error
    // must agree about where this response came from, and a second call could
    // not disagree but would invite one that does.
    const fromUpstream = cameFromUpstream(response, service);
    redirectToLoginOn401(response.status, fromUpstream);
    throw new ApiError(response.status, message, service, path, fromUpstream);
  }
  warnOnUnstampedSuccess(response, service, path);
  if (response.status === 204) return undefined as unknown as T;
  return (await response.json()) as T;
}

export async function fetchText(service: ProxyService, path: string): Promise<string> {
  const response = await fetch(proxyUrl(service, path), { cache: 'no-store' });
  if (!response.ok) {
    const message = await response.text().catch(() => '');
    const fromUpstream = cameFromUpstream(response, service);
    redirectToLoginOn401(response.status, fromUpstream);
    throw new ApiError(response.status, message, service, path, fromUpstream);
  }
  // Both success paths, not just fetchJson's: fetchText is an independent
  // reader of the same boundary (`/metrics`), and a detector wired into only
  // one of them would go quiet for whichever calls happen to use the other.
  warnOnUnstampedSuccess(response, service, path);
  return response.text();
}

// A native EventSource's `onerror` carries no HTTP status, so a caller can't
// tell "the operator session expired mid-connection" (401 — should redirect
// to /login) from an ordinary network blip (should just keep retrying) from
// the error event alone. Callers use this to confirm AFTER an SSE error,
// never before connecting: a pre-flight check would spend a request on every
// happy-path SSE open to guard a case (cold-load 401) every page already
// handles via its own gated fetchJson call before the stream ever opens. It
// issues one cheap gated GET and lets fetchJson's existing
// `redirectToLoginOn401` do the redirect if (and only if) the session really
// has expired; any other failure (network blip, upstream down) is not this
// helper's concern, so it's swallowed.
//
// "If and only if the session really has expired" is now literally true, and
// was not before: this probe reaches the control plane, so a rotated
// CONTROL_PLANE_API_KEY made it answer 401 with the operator's session
// perfectly valid — and an EventSource error then bounced them to /login.
// `redirectToLoginOn401` now reads the provenance stamp, so only a
// console-minted 401 (middleware's) redirects. Both hook tests mock this
// helper, so nothing there would catch a regression; `fetcher.test.ts` asserts
// it directly instead.
export async function confirmSessionOrRedirect(): Promise<void> {
  // Demo mode has no proxy session to confirm and must never touch the
  // proxy. Guarded here — not just by caller discipline — so a future
  // caller can't accidentally fire a real request from demo mode.
  if (usePreferencesStore.getState().demoMode) return;
  try {
    await fetchJson('control-plane', '/healthz');
  } catch {
    /* fetchJson already redirected if this was a 401 */
  }
}
