import { usePreferencesStore } from '@/lib/stores/preferences-store';
import type { ProxyService } from '@/lib/types';

// control-plane's GlobalExceptionFilter (src/errors/exception.filter.ts) formats
// structured errors as `{statusCode, errorCode, message, error: {code, message}}`
// with a top-level `errorCode` — `error.code` carries the same value, nested, as a
// fallback. Most call sites' bodies aren't JSON at all (plain text, an upstream's
// own error page), so a parse failure is expected, not exceptional — never let it
// mask the original HTTP error by throwing here.
function parseErrorCode(body: string): string | undefined {
  if (!body) return undefined;
  try {
    const parsed = JSON.parse(body) as { errorCode?: unknown; error?: { code?: unknown } };
    if (typeof parsed.errorCode === 'string') return parsed.errorCode;
    if (typeof parsed.error?.code === 'string') return parsed.error.code;
    return undefined;
  } catch {
    return undefined;
  }
}

export class ApiError extends Error {
  readonly status: number;
  readonly service: ProxyService;
  readonly path: string;
  /**
   * Structured upstream error code, when the body carried one.
   *
   * **Not control-plane-exclusive.** The top-level `errorCode` is the control
   * plane's (SCREAMING_SNAKE — `CONTEXT_ID_MISMATCH`,
   * `FEDERATION_UPSTREAM_RATE_LIMITED`), but the nested `error.code` fallback
   * above also matches the registry's own RFC-ACDP-0007 §5 wire envelope
   * (`acdp-registry-types/src/error.rs:83-92`), so a direct registry call
   * populates this with lowercase snake_case (`schema_violation`,
   * `rate_limited`, `not_authorized`). The two vocabularies do not collide
   * today, but nothing enforces that — so anything keyed by this value must
   * match exactly and must not infer provenance from the code alone. See
   * `lib/utils/api-error-messages.ts`.
   */
  readonly errorCode?: string;

  /**
   * The raw response text, verbatim — including `''` when the upstream sent
   * nothing.
   *
   * `message` is NOT a faithful carrier of this: the constructor falls back to
   * `Request failed with status ${status}` for an empty body, so a caller that
   * parsed `message` would be handing prose to `JSON.parse`. Callers that want
   * structured data out of a failure response (`pingHealth` reads the version
   * off a degraded `/healthz`) need the bytes, not the display string.
   *
   * Deliberately a raw string rather than an eagerly-parsed `bodyJson`:
   * `parseErrorCode` already parses this same text for its own purpose, and
   * most error bodies in this app are not JSON at all, so a second eager parse
   * would pay a cost on every error everywhere to serve one caller. Parsing
   * stays with the caller that wants it.
   */
  readonly body: string;

  /**
   * Whether these bytes actually came from the upstream service, or were
   * generated by this console before the request ever left the box.
   *
   * NOT inferable from `status`. The proxy route mints its own 400/403/502,
   * `middleware.ts` its own 401/403/503, and Next returns a 500 when the route
   * handler throws (an unset `*_BASE_URL` out of `getIntegrationConfig`) — so
   * a console-side 401 ("sign in at /login required") looks identical to an
   * upstream 401 if all you have is the number. The proxy stamps
   * `x-acdp-ui-proxy` on the pass-through path ONLY
   * (`app/api/proxy/[service]/[...path]/route.ts`), so its presence is a fact
   * rather than a guess.
   *
   * What it cannot tell you: whether the *service* answered or some
   * intermediary between the proxy and the service did (a reverse proxy's own
   * 504 is passed through and stamped). It answers "did this come from beyond
   * our own boundary", which is the honest limit of what the console knows.
   */
  readonly fromUpstream: boolean;

  constructor(status: number, body: string, service: ProxyService, path: string, fromUpstream = false) {
    super(body || `Request failed with status ${status}`);
    this.name = 'ApiError';
    this.status = status;
    this.service = service;
    this.path = path;
    this.body = body;
    this.fromUpstream = fromUpstream;
    this.errorCode = parseErrorCode(body);
  }

  get isNotFound() {
    return this.status === 404;
  }
}

export function proxyUrl(service: ProxyService, path: string): string {
  return `/api/proxy/${service}${path.startsWith('/') ? path : `/${path}`}`;
}

/**
 * Did these bytes cross our own boundary?
 *
 * The proxy route sets `x-acdp-ui-proxy` immediately before re-streaming an
 * upstream response and on no other path, so every envelope this console mints
 * itself — the route's 400/403/502, `middleware.ts`'s 401, 503 and
 * Origin-mismatch 403, and Next's 500 for an unset `*_BASE_URL` — arrives
 * without it. `proxy-route.test.ts` guards both directions: the stamp present
 * on pass-through, and absent on the route's own 403 and 502 envelopes.
 */
function cameFromUpstream(response: Response): boolean {
  return response.headers.get('x-acdp-ui-proxy') !== null;
}

// The proxy/stream gate (middleware.ts) returns 401 when the operator
// session is missing/invalid. Demo mode never reaches this: lib/api/client.ts
// returns mock data before touching fetchJson/fetchText, so this only fires
// in real mode.
//
// This runs outside any component (fetchJson/fetchText are plain module
// functions, often called from React Query's queryFn), so there's no
// `useRouter()` to reach for — a full navigation via `location.assign` is
// the correct tool here, not a lint smell.
function redirectToLoginOn401(status: number): void {
  if (status !== 401 || typeof window === 'undefined') return;
  if (window.location.pathname === '/login') return;
  // eslint-disable-next-line @next/next/no-location-assign-relative-destination
  window.location.assign('/login');
}

export async function fetchJson<T>(service: ProxyService, path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(proxyUrl(service, path), {
    ...init,
    headers: { 'content-type': 'application/json', ...(init?.headers ?? {}) },
    cache: 'no-store',
  });

  if (!response.ok) {
    const message = await response.text().catch(() => '');
    redirectToLoginOn401(response.status);
    throw new ApiError(response.status, message, service, path, cameFromUpstream(response));
  }
  if (response.status === 204) return undefined as unknown as T;
  return (await response.json()) as T;
}

export async function fetchText(service: ProxyService, path: string): Promise<string> {
  const response = await fetch(proxyUrl(service, path), { cache: 'no-store' });
  if (!response.ok) {
    const message = await response.text().catch(() => '');
    redirectToLoginOn401(response.status);
    throw new ApiError(response.status, message, service, path, cameFromUpstream(response));
  }
  return response.text();
}

// A native EventSource's `onerror` carries no HTTP status, so a caller can't
// tell "the operator session expired mid-connection" (401 — should redirect
// to /login) from an ordinary network blip (should just keep retrying) from
// the error event alone. Callers use this to confirm AFTER an SSE error,
// never before connecting: a pre-flight check would spend a request on every
// happy-path SSE open to guard a case (cold-load 401) every page already
// handles via its own gated fetchJson call before the stream ever opens. It
// issues one cheap gated GET and lets fetchJson's existing
// `redirectToLoginOn401` do the redirect if (and only if) the session really
// has expired; any other failure (network blip, upstream down) is not this
// helper's concern, so it's swallowed.
export async function confirmSessionOrRedirect(): Promise<void> {
  // Demo mode has no proxy session to confirm and must never touch the
  // proxy. Guarded here — not just by caller discipline — so a future
  // caller can't accidentally fire a real request from demo mode.
  if (usePreferencesStore.getState().demoMode) return;
  try {
    await fetchJson('control-plane', '/healthz');
  } catch {
    /* fetchJson already redirected if this was a 401 */
  }
}
