// ══════════════════════════════════════════════════════════════════════
// GENERATED by scripts/gen-mock-crypto.mjs — DO NOT EDIT BY HAND.
//
// Real ACDP cryptographic material for the demo dataset: every content_hash,
// producer signature, registry receipt, lineage-head receipt, transparency-log
// checkpoint + inclusion proof, and witness cosignature below was minted with
// actual Ed25519 / ECDSA-P256 keys and SELF-VERIFIED through the same
// @agentcontextdistributionprotocol/acdp-wasm verifier the browser runs. The
// generator throws if any surface fails to verify, so these values are known-good.
//
// Regenerate:  node scripts/gen-mock-crypto.mjs
// ══════════════════════════════════════════════════════════════════════

export const DID_KEY_PRODUCER = "did:key:z6MktwtqAzuD5F77tAMBMwNs1KybZeff61EehV9xB1ZpXQG7";
export const WITNESS_BETA_DID = "did:key:z6Mki11Bt3TszrQcX7c1GuaNUc3gFh4XLWjCQWXrRis9QQeH";
export const LIN_ATTESTED = "lin:sha256:444ce9e4045a12619d57eabb8524a0e54f6e9cf322f6dd1092612c8b54313039";

/** did:web DID documents the console resolves offline in demo mode. */
export const MOCK_DID_DOCS: Record<string, unknown> = {
  "did:web:registry-a.local:agents:cross-a": {
    "id": "did:web:registry-a.local:agents:cross-a",
    "verificationMethod": [
      {
        "id": "did:web:registry-a.local:agents:cross-a#key-1",
        "type": "Ed25519VerificationKey2020",
        "controller": "did:web:registry-a.local:agents:cross-a",
        "publicKeyMultibase": "z6MkqGC3nWZhYieEVTVDKW5v588CiGfsDSmRVG9ZwwWTvLSK"
      }
    ],
    "assertionMethod": [
      "did:web:registry-a.local:agents:cross-a#key-1"
    ]
  },
  "did:web:registry-b.local:agents:cross-b": {
    "id": "did:web:registry-b.local:agents:cross-b",
    "verificationMethod": [
      {
        "id": "did:web:registry-b.local:agents:cross-b#key-2",
        "type": "JsonWebKey2020",
        "controller": "did:web:registry-b.local:agents:cross-b",
        "publicKeyJwk": {
          "kty": "EC",
          "crv": "P-256",
          "x": "jtuP0OyDzPGA1SnhX6W_9nSHoSTrlaDirIIXpqzRyRM",
          "y": "S97gg87gJmk_XeFXLUSYA-dbA7s9qy_JqViYFEMuhgw"
        }
      }
    ],
    "assertionMethod": [
      "did:web:registry-b.local:agents:cross-b#key-2"
    ]
  },
  "did:web:registry-a.local:agents:solo": {
    "id": "did:web:registry-a.local:agents:solo",
    "verificationMethod": [
      {
        "id": "did:web:registry-a.local:agents:solo#key-1",
        "type": "Ed25519VerificationKey2020",
        "controller": "did:web:registry-a.local:agents:solo",
        "publicKeyMultibase": "z6Mkg49NtQR2LyYRDCQFK4w1VVHqhypZSSRo7HsyuN7SV7v5"
      }
    ],
    "assertionMethod": [
      "did:web:registry-a.local:agents:solo#key-1"
    ]
  },
  "did:web:registry-a.playground.local": {
    "id": "did:web:registry-a.playground.local",
    "verificationMethod": [
      {
        "id": "did:web:registry-a.playground.local#receipt-key-1",
        "type": "Ed25519VerificationKey2020",
        "controller": "did:web:registry-a.playground.local",
        "publicKeyMultibase": "z6Mkhu4BLQGcYCtgBVYdM7TgYcGyg6TXqGcnbpdY8ufABFsz"
      }
    ],
    "assertionMethod": [
      "did:web:registry-a.playground.local#receipt-key-1"
    ]
  },
  "did:web:registry-c.playground.local": {
    "id": "did:web:registry-c.playground.local",
    "verificationMethod": [
      {
        "id": "did:web:registry-c.playground.local#receipt-key-1",
        "type": "Ed25519VerificationKey2020",
        "controller": "did:web:registry-c.playground.local",
        "publicKeyMultibase": "z6MktULudTtAsAhRegYPiZ6631RV3viv12qd4GQF8z1xB22S"
      }
    ],
    "assertionMethod": [
      "did:web:registry-c.playground.local#receipt-key-1"
    ]
  },
  "did:web:witness-alpha.trust.example": {
    "id": "did:web:witness-alpha.trust.example",
    "verificationMethod": [
      {
        "id": "did:web:witness-alpha.trust.example#witness-key-1",
        "type": "Ed25519VerificationKey2020",
        "controller": "did:web:witness-alpha.trust.example",
        "publicKeyMultibase": "z6Mksp9sfVKVpWAi43niHLXfGQ5NdCTEoiycLmrLPehquVqK"
      }
    ],
    "assertionMethod": [
      "did:web:witness-alpha.trust.example#witness-key-1"
    ]
  }
};

/** Per-context crypto material (hashed body fields + signatures + trust proofs). */
export const MOCK_CRYPTO = {
  "arcticSource": {
    "hashed": {
      "version": 1,
      "agent_id": "did:web:registry-a.local:agents:cross-a",
      "title": "Cross-registry source — Arctic shipping routes",
      "type": "data_snapshot",
      "visibility": "public",
      "derived_from": [],
      "summary": "Geopolitical and logistical assessment of emerging Arctic shipping corridors.",
      "description": "Composite snapshot fusing AIS vessel traffic, ice-coverage telemetry, and port throughput for the 2024 navigation season.",
      "tags": [
        "geopolitics",
        "logistics"
      ],
      "domain": "geopolitics",
      "acdp_version": "0.1.0",
      "supersedes": null,
      "contributors": [
        "did:web:registry-a.local:agents:cross-a"
      ],
      "data_refs": [
        {
          "type": "data_snapshot",
          "location": "s3://acdp-demo/arctic/ais-2024.parquet",
          "encoding": "application/parquet"
        }
      ],
      "data_period": {
        "start": "2026-03-01T00:00:00.000Z",
        "end": "2026-07-01T00:00:00.000Z"
      },
      "expires_at": "2026-08-01T00:00:00.000Z",
      "schema_uri": "https://schemas.acdp.dev/data_snapshot/v1.json"
    },
    "content_hash": "sha256:6ba93efc90838d34baea133a7c6287dbb9870d48f64b9cac0d057f61739a274b",
    "signature": {
      "algorithm": "ed25519",
      "key_id": "did:web:registry-a.local:agents:cross-a#key-1",
      "value": "JabEEyX1z4z8Ogbqi5qtYlvm0U5c5irr0e5Ev5a53xrHjElSrpGmgEbqlaH6FjBTlHBawCvQez9uvTtpfqzVDA=="
    },
    "registry_receipt": {
      "registry_did": "did:web:registry-a.playground.local",
      "ctx_id": "acdp://registry-a.playground.local/f4a2c9e1-1d2b-4a3c-9e8f-001",
      "lineage_id": "lin-arctic-001",
      "origin_registry": "registry-a.playground.local",
      "created_at": "2026-07-06T12:00:00.000Z",
      "content_hash": "sha256:6ba93efc90838d34baea133a7c6287dbb9870d48f64b9cac0d057f61739a274b",
      "key_fingerprint": "sha256:1325b850c2871916eae203f0efc3c8987f64e5e3cdb27679e6d1fa97808357e6",
      "signature": {
        "algorithm": "ed25519",
        "key_id": "did:web:registry-a.playground.local#receipt-key-1",
        "value": "YiZRKIwzg2jXeo1EMvU3EAvqnwn7tlxaR6mp900OUVk0JVNFHFIky63Srl/KyPLHczIFSYD+woV1lcIJsOHiDQ=="
      }
    }
  },
  "arcticDeriv": {
    "hashed": {
      "version": 1,
      "agent_id": "did:web:registry-b.local:agents:cross-b",
      "title": "Cross-registry derivative — Arctic investment analysis",
      "type": "analysis",
      "visibility": "public",
      "derived_from": [
        "acdp://registry-a.playground.local/f4a2c9e1-1d2b-4a3c-9e8f-001"
      ],
      "summary": "Investment implications derived from the Arctic shipping snapshot.",
      "description": "Risk-weighted investment thesis across shipping, insurance, and port-infrastructure equities.",
      "tags": [
        "investment",
        "analysis"
      ],
      "domain": "finance",
      "acdp_version": "0.1.0",
      "supersedes": null,
      "contributors": [
        "did:web:registry-b.local:agents:cross-b",
        "did:web:registry-a.local:agents:cross-a"
      ],
      "audience": [
        "did:web:registry-a.local:agents:cross-a"
      ],
      "data_refs": [
        {
          "type": "report",
          "location": "https://reports.acdp-demo/arctic-investment.pdf",
          "encoding": "application/pdf"
        }
      ],
      "schema_uri": "https://schemas.acdp.dev/analysis/v1.json"
    },
    "content_hash": "sha256:39e26dcd3f1a43989c9b51d59bedd20acee77dcd68d7d57bcdc40928649b3df6",
    "signature": {
      "algorithm": "ecdsa-p256",
      "key_id": "did:web:registry-b.local:agents:cross-b#key-2",
      "value": "QkcoaRWEoIlCe9ph6A67d/ig8o4af/KPZWXgA36RjAt6BiITyg9YpKSq7zrK6QK92Rg9Vh9hIor2kn3ihv+Lqw=="
    }
  },
  "cashV1": {
    "hashed": {
      "version": 1,
      "agent_id": "did:web:registry-a.local:agents:solo",
      "title": "Quarterly cash flow snapshot",
      "type": "data_snapshot",
      "visibility": "public",
      "derived_from": [],
      "summary": "Snapshot of quarterly operating cash flow figures.",
      "description": "Operating, investing, and financing cash flows for the trailing quarter.",
      "tags": [
        "finance"
      ],
      "domain": "finance",
      "acdp_version": "0.1.0",
      "supersedes": null,
      "contributors": [
        "did:web:registry-a.local:agents:solo"
      ],
      "data_refs": [
        {
          "type": "data_snapshot",
          "location": "s3://acdp-demo/finance/cashflow-q.json",
          "encoding": "application/json"
        }
      ],
      "data_period": {
        "start": "2026-04-01T00:00:00.000Z",
        "end": "2026-07-01T00:00:00.000Z"
      }
    },
    "content_hash": "sha256:7e3496e2bcecfc3958ebbde558cc853149b8e16481c815f61c642a72d73c0f60",
    "signature": {
      "algorithm": "ed25519",
      "key_id": "did:web:registry-a.local:agents:solo#key-1",
      "value": "1XIcEPJQHG7OLvnepEJpLV6YuKimEaNO6DxK3Xv1jk/wMy3QavnVnlKdiwETkpN41RVqNh79Pl4NVJufLLY3AA=="
    }
  },
  "cashV2": {
    "hashed": {
      "version": 2,
      "agent_id": "did:web:registry-a.local:agents:solo",
      "title": "Quarterly cash flow snapshot (revised)",
      "type": "data_snapshot",
      "visibility": "public",
      "derived_from": [],
      "summary": "Revised quarterly operating cash flow figures after reconciliation.",
      "description": "Operating, investing, and financing cash flows for the trailing quarter.",
      "tags": [
        "finance"
      ],
      "domain": "finance",
      "acdp_version": "0.1.0",
      "supersedes": "acdp://registry-a.playground.local/2e78f01a-solo",
      "contributors": [
        "did:web:registry-a.local:agents:solo"
      ],
      "data_refs": [
        {
          "type": "data_snapshot",
          "location": "s3://acdp-demo/finance/cashflow-q.json",
          "encoding": "application/json"
        }
      ],
      "data_period": {
        "start": "2026-04-01T00:00:00.000Z",
        "end": "2026-07-01T00:00:00.000Z"
      }
    },
    "content_hash": "sha256:82324661d6f313d37ff6c3b5d5e06f1300f3a0eea82f4eefba979a7dd8e08c22",
    "signature": {
      "algorithm": "ed25519",
      "key_id": "did:web:registry-a.local:agents:solo#key-1",
      "value": "7C2l/Vu5Atk+hOVqB1I9rjmn4OaAJS2HU8uOEPK56xnwDIlM37qEVnvRUsTJJe2O9fH9jy2b+fDMJYJvFS76AQ=="
    }
  },
  "attested": {
    "hashed": {
      "version": 1,
      "agent_id": "did:key:z6MktwtqAzuD5F77tAMBMwNs1KybZeff61EehV9xB1ZpXQG7",
      "title": "Attested disclosure — did:key ephemeral agent",
      "type": "attestation",
      "visibility": "public",
      "derived_from": [],
      "summary": "Offline-verifiable disclosure published by an ephemeral did:key agent to the receipts registry.",
      "description": "Demonstrates the RFC-ACDP-0010 receipts profile: the producer key is embedded in the did:key identifier and pinned by the registry receipt.",
      "tags": [
        "attestation",
        "did:key"
      ],
      "domain": "compliance",
      "acdp_version": "0.2.0",
      "supersedes": null,
      "contributors": [
        "did:key:z6MktwtqAzuD5F77tAMBMwNs1KybZeff61EehV9xB1ZpXQG7"
      ]
    },
    "content_hash": "sha256:e58ed2540ab5a4db348e3d9e97fc7b501c5aa50ae1fa7fde5613e92bbb120a27",
    "signature": {
      "algorithm": "ed25519",
      "key_id": "did:key:z6MktwtqAzuD5F77tAMBMwNs1KybZeff61EehV9xB1ZpXQG7#z6MktwtqAzuD5F77tAMBMwNs1KybZeff61EehV9xB1ZpXQG7",
      "value": "r3vpinQs5HY8m9GUp7hNc3GAlTZRYDc/OBr0kaJlqrlb00Nyk+VMWojjvSJVTieSAQaNeKjM7qJrUHjMef4jAA=="
    },
    "registry_receipt": {
      "registry_did": "did:web:registry-c.playground.local",
      "ctx_id": "acdp://registry-c.playground.local/attested-001",
      "lineage_id": "lin:sha256:444ce9e4045a12619d57eabb8524a0e54f6e9cf322f6dd1092612c8b54313039",
      "origin_registry": "registry-c.playground.local",
      "created_at": "2026-07-06T12:00:00.000Z",
      "content_hash": "sha256:e58ed2540ab5a4db348e3d9e97fc7b501c5aa50ae1fa7fde5613e92bbb120a27",
      "key_fingerprint": "sha256:b14705888f4a68391a09aa5968dd25d16c3bba7bb3b6d15bf354d8dcaae85a47",
      "signature": {
        "algorithm": "ed25519",
        "key_id": "did:web:registry-c.playground.local#receipt-key-1",
        "value": "GrfMHCSZx4QQxAOLpHQdlaOJ9DhL9r0kneMErWTXfMJJFk1+gfcrLDw7Xf4s0sV3hMOj86UakuJNUElAlhBJDQ=="
      }
    },
    "lineage_head_receipt": {
      "receipt_version": "acdp-lhr/1",
      "registry_did": "did:web:registry-c.playground.local",
      "lineage_id": "lin:sha256:444ce9e4045a12619d57eabb8524a0e54f6e9cf322f6dd1092612c8b54313039",
      "head_ctx_id": "acdp://registry-c.playground.local/attested-001",
      "head_version": 1,
      "head_status": "active",
      "as_of": "2026-07-06T12:34:00.000Z",
      "signature": {
        "algorithm": "ed25519",
        "key_id": "did:web:registry-c.playground.local#receipt-key-1",
        "value": "uRxt7dpe+WykThoaWDxELLA/4p+t6MlxHRepr4tj0yAFMPgrPrW6bXTxuDvXvzWZydqfPSDXGWVu5eDyzSSwDw=="
      }
    },
    "log_inclusion": {
      "log_id": "did:web:registry-c.playground.local/log/receipts",
      "leaf_index": 2,
      "tree_size": 6,
      "inclusion_path": [
        "sha256:9fc5c5c71fb62d30486cf1c710eb0ec39c5f9ad6d2200d5a5ec2075b716a06c8",
        "sha256:70a84d58635cf6e4e301576d5803100faef744f8f17cc3baa4269e0c1f7fed20",
        "sha256:c116f45f3924412d74b248d8d2713dfbb32e058dfb9bf13ccdc55cefb8829e1b"
      ],
      "log_checkpoint": {
        "checkpoint_version": "acdp-log/1",
        "log_id": "did:web:registry-c.playground.local/log/receipts",
        "tree_size": 6,
        "root_hash": "sha256:2d81735f9de80063ffb2d96ae64fb87687df67f87bcfef256737c6487ae6ef92",
        "timestamp": "2026-07-06T12:34:00.000Z",
        "signature": {
          "algorithm": "ed25519",
          "key_id": "did:web:registry-c.playground.local#receipt-key-1",
          "value": "e+z87X2FYMJY0kSVBE0F7552TJdHGsO1r0gEzBM33OKNOCkclgTMmfEHWnMotIb0MxWwIyPOvbSWbOeop+hTDw=="
        }
      },
      "witness_signatures": [
        {
          "cosignature_version": "acdp-cosig/1",
          "witness_id": "did:web:witness-alpha.trust.example",
          "witnessed_checkpoint": {
            "log_id": "did:web:registry-c.playground.local/log/receipts",
            "tree_size": 6,
            "root_hash": "sha256:2d81735f9de80063ffb2d96ae64fb87687df67f87bcfef256737c6487ae6ef92",
            "timestamp": "2026-07-06T12:34:00.000Z"
          },
          "witnessed_at": "2026-07-06T12:35:00.000Z",
          "signature": {
            "algorithm": "ed25519",
            "key_id": "did:web:witness-alpha.trust.example#witness-key-1",
            "value": "zwwxCRvwqig86r57sPkaLGK8qzdfNJv8aHN57lRy6XHAPAiX6s1bIpt5PDVhODm+Cif7rBb35DL9sAB5bFj0Aw=="
          }
        },
        {
          "cosignature_version": "acdp-cosig/1",
          "witness_id": "did:key:z6Mki11Bt3TszrQcX7c1GuaNUc3gFh4XLWjCQWXrRis9QQeH",
          "witnessed_checkpoint": {
            "log_id": "did:web:registry-c.playground.local/log/receipts",
            "tree_size": 6,
            "root_hash": "sha256:2d81735f9de80063ffb2d96ae64fb87687df67f87bcfef256737c6487ae6ef92",
            "timestamp": "2026-07-06T12:34:00.000Z"
          },
          "witnessed_at": "2026-07-06T12:33:00.000Z",
          "signature": {
            "algorithm": "ed25519",
            "key_id": "did:key:z6Mki11Bt3TszrQcX7c1GuaNUc3gFh4XLWjCQWXrRis9QQeH#witness-key-1",
            "value": "TfxGzZ7wO85PKEwaYdVkr4BAppk4WAd2n63Vk+okaxG4RyeycEB/P4xw6Sbw0XAlCnWzti1Tnt9rnCzlL87dCQ=="
          }
        }
      ]
    }
  }
};
