// ══════════════════════════════════════════════════════════════════════
// GENERATED by scripts/gen-mock-crypto.mjs — DO NOT EDIT BY HAND.
//
// Real ACDP cryptographic material for the demo dataset: every content_hash,
// producer signature, registry receipt, lineage-head receipt, transparency-log
// checkpoint + inclusion proof, and witness cosignature below was minted with
// actual Ed25519 / ECDSA-P256 keys and SELF-VERIFIED through the same
// @agentcontextdistributionprotocol/acdp-wasm verifier the browser runs. The
// generator throws if any surface fails to verify, so these values are known-good.
//
// Regenerate:  node scripts/gen-mock-crypto.mjs
// ══════════════════════════════════════════════════════════════════════

export const DID_KEY_PRODUCER = "did:key:z6MktwtqAzuD5F77tAMBMwNs1KybZeff61EehV9xB1ZpXQG7";
export const WITNESS_BETA_DID = "did:key:z6Mki11Bt3TszrQcX7c1GuaNUc3gFh4XLWjCQWXrRis9QQeH";
export const LIN_ATTESTED = "lin:sha256:444ce9e4045a12619d57eabb8524a0e54f6e9cf322f6dd1092612c8b54313039";

/** did:web DID documents the console resolves offline in demo mode. */
export const MOCK_DID_DOCS: Record<string, unknown> = {
  "did:web:registry-a.local:agents:cross-a": {
    "id": "did:web:registry-a.local:agents:cross-a",
    "verificationMethod": [
      {
        "id": "did:web:registry-a.local:agents:cross-a#key-1",
        "type": "Ed25519VerificationKey2020",
        "controller": "did:web:registry-a.local:agents:cross-a",
        "publicKeyMultibase": "z6MkqGC3nWZhYieEVTVDKW5v588CiGfsDSmRVG9ZwwWTvLSK"
      }
    ],
    "assertionMethod": [
      "did:web:registry-a.local:agents:cross-a#key-1"
    ]
  },
  "did:web:registry-b.local:agents:cross-b": {
    "id": "did:web:registry-b.local:agents:cross-b",
    "verificationMethod": [
      {
        "id": "did:web:registry-b.local:agents:cross-b#key-2",
        "type": "JsonWebKey2020",
        "controller": "did:web:registry-b.local:agents:cross-b",
        "publicKeyJwk": {
          "kty": "EC",
          "crv": "P-256",
          "x": "GtnGuvmDDkITG-kcYOTh-7yowG-IBdxG2LisHYPnopc",
          "y": "A3QK5g1wzDvZ0p0abBtwAYX4lHLte1VPcVyX38-NUxU"
        }
      }
    ],
    "assertionMethod": [
      "did:web:registry-b.local:agents:cross-b#key-2"
    ]
  },
  "did:web:registry-a.local:agents:solo": {
    "id": "did:web:registry-a.local:agents:solo",
    "verificationMethod": [
      {
        "id": "did:web:registry-a.local:agents:solo#key-1",
        "type": "Ed25519VerificationKey2020",
        "controller": "did:web:registry-a.local:agents:solo",
        "publicKeyMultibase": "z6Mkg49NtQR2LyYRDCQFK4w1VVHqhypZSSRo7HsyuN7SV7v5"
      }
    ],
    "assertionMethod": [
      "did:web:registry-a.local:agents:solo#key-1"
    ]
  },
  "did:web:registry-a.playground.local": {
    "id": "did:web:registry-a.playground.local",
    "verificationMethod": [
      {
        "id": "did:web:registry-a.playground.local#receipt-key-1",
        "type": "Ed25519VerificationKey2020",
        "controller": "did:web:registry-a.playground.local",
        "publicKeyMultibase": "z6Mkhu4BLQGcYCtgBVYdM7TgYcGyg6TXqGcnbpdY8ufABFsz"
      }
    ],
    "assertionMethod": [
      "did:web:registry-a.playground.local#receipt-key-1"
    ]
  },
  "did:web:witness-alpha.trust.example": {
    "id": "did:web:witness-alpha.trust.example",
    "verificationMethod": [
      {
        "id": "did:web:witness-alpha.trust.example#witness-key-1",
        "type": "Ed25519VerificationKey2020",
        "controller": "did:web:witness-alpha.trust.example",
        "publicKeyMultibase": "z6Mksp9sfVKVpWAi43niHLXfGQ5NdCTEoiycLmrLPehquVqK"
      }
    ],
    "assertionMethod": [
      "did:web:witness-alpha.trust.example#witness-key-1"
    ]
  }
};

/** Per-context crypto material (hashed body fields + signatures + trust proofs). */
export const MOCK_CRYPTO = {
  "arcticSource": {
    "hashed": {
      "version": 1,
      "agent_id": "did:web:registry-a.local:agents:cross-a",
      "title": "Cross-registry source — Arctic shipping routes",
      "type": "data_snapshot",
      "visibility": "public",
      "derived_from": [],
      "summary": "Geopolitical and logistical assessment of emerging Arctic shipping corridors.",
      "description": "Composite snapshot fusing AIS vessel traffic, ice-coverage telemetry, and port throughput for the 2024 navigation season.",
      "tags": [
        "geopolitics",
        "logistics"
      ],
      "domain": "geopolitics",
      "acdp_version": "0.1.0",
      "supersedes": null,
      "contributors": [
        "did:web:registry-a.local:agents:cross-a"
      ],
      "data_refs": [
        {
          "type": "primary_result",
          "location": "s3://acdp-demo/arctic/ais-2024.parquet",
          "encoding": "application/parquet"
        }
      ],
      "data_period": {
        "start": "2026-03-01T00:00:00.000Z",
        "end": "2026-07-01T00:00:00.000Z"
      },
      "expires_at": "2026-08-01T00:00:00.000Z",
      "schema_uri": "https://schemas.acdp.dev/data_snapshot/v1.json"
    },
    "content_hash": "sha256:a8363bda3152efa5214d1ed9700789062a338664f566e369383deaaaa61c5d40",
    "signature": {
      "algorithm": "ed25519",
      "key_id": "did:web:registry-a.local:agents:cross-a#key-1",
      "value": "Ln65F8XoN5xkWBh5uZp9UMa22x0ThSXZot6M/rOR48oijKwOmyf7y8+8X3YvuQmCi/ul2NTy8O9JREbJzvSbDA=="
    },
    "registry_receipt": {
      "registry_did": "did:web:registry-a.playground.local",
      "ctx_id": "acdp://registry-a.playground.local/d1feb434-ef44-4166-b3ac-a157f795661d",
      "lineage_id": "lin-arctic-001",
      "origin_registry": "registry-a.playground.local",
      "created_at": "2026-07-06T11:59:00.000Z",
      "content_hash": "sha256:a8363bda3152efa5214d1ed9700789062a338664f566e369383deaaaa61c5d40",
      "key_fingerprint": "sha256:1325b850c2871916eae203f0efc3c8987f64e5e3cdb27679e6d1fa97808357e6",
      "signature": {
        "algorithm": "ed25519",
        "key_id": "did:web:registry-a.playground.local#receipt-key-1",
        "value": "JSwz1t6Vk5kqOEED58YmMJAqhgpgr2TNHrRlerNopn3T1eGekIIJXD9WYsV021EtShgArpVzPngmQh7Tj24FDg=="
      }
    }
  },
  "arcticDeriv": {
    "hashed": {
      "version": 1,
      "agent_id": "did:web:registry-b.local:agents:cross-b",
      "title": "Cross-registry derivative — Arctic investment analysis",
      "type": "analysis",
      "visibility": "public",
      "derived_from": [
        "acdp://registry-a.playground.local/d1feb434-ef44-4166-b3ac-a157f795661d"
      ],
      "summary": "Investment implications derived from the Arctic shipping snapshot.",
      "description": "Risk-weighted investment thesis across shipping, insurance, and port-infrastructure equities.",
      "tags": [
        "investment",
        "analysis"
      ],
      "domain": "finance",
      "acdp_version": "0.1.0",
      "supersedes": null,
      "contributors": [
        "did:web:registry-b.local:agents:cross-b",
        "did:web:registry-a.local:agents:cross-a"
      ],
      "audience": [
        "did:web:registry-a.local:agents:cross-a"
      ],
      "data_refs": [
        {
          "type": "primary_result",
          "location": "https://reports.acdp-demo/arctic-investment.pdf",
          "encoding": "application/pdf"
        }
      ],
      "schema_uri": "https://schemas.acdp.dev/analysis/v1.json"
    },
    "content_hash": "sha256:9b0dcb87802b8f753d24515f39e7a8f3e1376b6177db0034b1cc8712cf45177d",
    "signature": {
      "algorithm": "ecdsa-p256",
      "key_id": "did:web:registry-b.local:agents:cross-b#key-2",
      "value": "8O3hLLqYWF3Zg7+fsoIhg4fU2+Yd6H06cq7QktbN3bz53bTkEfmUmLUZh9Zg2CLadXRg41iQWZPypIcCFzySSA=="
    }
  },
  "cashV1": {
    "hashed": {
      "version": 1,
      "agent_id": "did:web:registry-a.local:agents:solo",
      "title": "Quarterly cash flow snapshot",
      "type": "data_snapshot",
      "visibility": "public",
      "derived_from": [],
      "summary": "Snapshot of quarterly operating cash flow figures.",
      "description": "Operating, investing, and financing cash flows for the trailing quarter.",
      "tags": [
        "finance"
      ],
      "domain": "finance",
      "acdp_version": "0.1.0",
      "supersedes": null,
      "contributors": [
        "did:web:registry-a.local:agents:solo"
      ],
      "data_refs": [
        {
          "type": "primary_result",
          "location": "s3://acdp-demo/finance/cashflow-q.json",
          "encoding": "application/json"
        }
      ],
      "data_period": {
        "start": "2026-04-01T00:00:00.000Z",
        "end": "2026-07-01T00:00:00.000Z"
      }
    },
    "content_hash": "sha256:3cd0e74a913011ae4056d41084292f66953de0a8bbeeb800ab6ec67028df3c3a",
    "signature": {
      "algorithm": "ed25519",
      "key_id": "did:web:registry-a.local:agents:solo#key-1",
      "value": "G8y6jndztDiLFA2Xc4riUTD1jMR3gyptFLGE/kXD4aPn1K22YDmAU4y8PGY6XjIoZm73q0Xn0Xw/Ow/TokeYAA=="
    }
  },
  "cashV2": {
    "hashed": {
      "version": 2,
      "agent_id": "did:web:registry-a.local:agents:solo",
      "title": "Quarterly cash flow snapshot (revised)",
      "type": "data_snapshot",
      "visibility": "public",
      "derived_from": [],
      "summary": "Revised quarterly operating cash flow figures after reconciliation.",
      "description": "Operating, investing, and financing cash flows for the trailing quarter.",
      "tags": [
        "finance"
      ],
      "domain": "finance",
      "acdp_version": "0.1.0",
      "supersedes": "acdp://registry-a.playground.local/94a58a84-b576-47d7-a73e-d04edf9c95de",
      "contributors": [
        "did:web:registry-a.local:agents:solo"
      ],
      "data_refs": [
        {
          "type": "primary_result",
          "location": "s3://acdp-demo/finance/cashflow-q.json",
          "encoding": "application/json"
        }
      ],
      "data_period": {
        "start": "2026-04-01T00:00:00.000Z",
        "end": "2026-07-01T00:00:00.000Z"
      }
    },
    "content_hash": "sha256:95a01ae5de0f321b4428687ae305bee0fd4e655dab5c84407d1ab54ad806f455",
    "signature": {
      "algorithm": "ed25519",
      "key_id": "did:web:registry-a.local:agents:solo#key-1",
      "value": "vop4Y7Ch6x8jeEgoJ+56OX/un4APZo6l97IbUMrCzLRg89tZC81egMlMQKZYjQKHKP3vKMRdzAeID24aLGscCg=="
    }
  },
  "attested": {
    "hashed": {
      "version": 1,
      "agent_id": "did:key:z6MktwtqAzuD5F77tAMBMwNs1KybZeff61EehV9xB1ZpXQG7",
      "title": "Attested disclosure — did:key ephemeral agent",
      "type": "demo:attestation",
      "visibility": "public",
      "derived_from": [],
      "summary": "Offline-verifiable disclosure published by an ephemeral did:key agent to the receipts registry.",
      "description": "Demonstrates the RFC-ACDP-0010 receipts profile: the producer key is embedded in the did:key identifier and pinned by the registry receipt.",
      "tags": [
        "attestation",
        "did:key"
      ],
      "domain": "compliance",
      "acdp_version": "0.2.0",
      "supersedes": null,
      "contributors": [
        "did:key:z6MktwtqAzuD5F77tAMBMwNs1KybZeff61EehV9xB1ZpXQG7"
      ],
      "data_refs": []
    },
    "content_hash": "sha256:93b42b5d4a88bf55f059ccc2e7bfc2d259af86cbea0b56cf8938233ab5e8427e",
    "signature": {
      "algorithm": "ed25519",
      "key_id": "did:key:z6MktwtqAzuD5F77tAMBMwNs1KybZeff61EehV9xB1ZpXQG7#z6MktwtqAzuD5F77tAMBMwNs1KybZeff61EehV9xB1ZpXQG7",
      "value": "2PWcX0m2OcFw+zGkxx4n0viQbFj58rF/kHP6pSjfoCINrX7+SPd/SSF6i8yqyRYhXpkTw8sdf7e8hPAzDeDjAw=="
    },
    "registry_receipt": {
      "registry_did": "did:web:registry-a.playground.local",
      "ctx_id": "acdp://registry-a.playground.local/5dcdb05d-bfbc-4088-936b-da19eec25319",
      "lineage_id": "lin:sha256:444ce9e4045a12619d57eabb8524a0e54f6e9cf322f6dd1092612c8b54313039",
      "origin_registry": "registry-a.playground.local",
      "created_at": "2026-07-06T11:57:00.000Z",
      "content_hash": "sha256:93b42b5d4a88bf55f059ccc2e7bfc2d259af86cbea0b56cf8938233ab5e8427e",
      "key_fingerprint": "sha256:b14705888f4a68391a09aa5968dd25d16c3bba7bb3b6d15bf354d8dcaae85a47",
      "signature": {
        "algorithm": "ed25519",
        "key_id": "did:web:registry-a.playground.local#receipt-key-1",
        "value": "KvJdL/tISfSbRAlzvDuzG/B2+UJB/nNfmHRkc4EKS8MwNdhslogVejLWIjEzjXeNhJd3wEi9YMdWEUfszWjMAg=="
      }
    },
    "lineage_head_receipt": {
      "receipt_version": "acdp-lhr/1",
      "registry_did": "did:web:registry-a.playground.local",
      "lineage_id": "lin:sha256:444ce9e4045a12619d57eabb8524a0e54f6e9cf322f6dd1092612c8b54313039",
      "head_ctx_id": "acdp://registry-a.playground.local/5dcdb05d-bfbc-4088-936b-da19eec25319",
      "head_version": 1,
      "head_status": "active",
      "as_of": "2026-07-06T12:34:00.000Z",
      "signature": {
        "algorithm": "ed25519",
        "key_id": "did:web:registry-a.playground.local#receipt-key-1",
        "value": "UCaUQBY+MC/rmfH81P72vnre7h8VHUwWCs0a6UcD94YbN3COBtBDMmETdVeYU+6itSIxBU/bAlIzgFH9Cr3jBA=="
      }
    },
    "log_inclusion": {
      "log_id": "did:web:registry-a.playground.local/log/receipts",
      "leaf_index": 2,
      "tree_size": 6,
      "inclusion_path": [
        "sha256:9fc5c5c71fb62d30486cf1c710eb0ec39c5f9ad6d2200d5a5ec2075b716a06c8",
        "sha256:70a84d58635cf6e4e301576d5803100faef744f8f17cc3baa4269e0c1f7fed20",
        "sha256:c116f45f3924412d74b248d8d2713dfbb32e058dfb9bf13ccdc55cefb8829e1b"
      ],
      "log_checkpoint": {
        "checkpoint_version": "acdp-log/1",
        "log_id": "did:web:registry-a.playground.local/log/receipts",
        "tree_size": 6,
        "root_hash": "sha256:d93fc06ae8e2dc9b3ea7c24060d3d9cfea9720eebc1aef1f06a9ae74de9c592c",
        "timestamp": "2026-07-06T12:34:00.000Z",
        "signature": {
          "algorithm": "ed25519",
          "key_id": "did:web:registry-a.playground.local#receipt-key-1",
          "value": "Zz0FoEQiruWwq8iHH7HKVvNATFDTohteU1UeXcuuQVJEyfSMhb68s1powio2Fyn3G2onqHjmULMM1OBqWMdhCA=="
        }
      },
      "witness_signatures": [
        {
          "cosignature_version": "acdp-cosig/1",
          "witness_id": "did:web:witness-alpha.trust.example",
          "witnessed_checkpoint": {
            "log_id": "did:web:registry-a.playground.local/log/receipts",
            "tree_size": 6,
            "root_hash": "sha256:d93fc06ae8e2dc9b3ea7c24060d3d9cfea9720eebc1aef1f06a9ae74de9c592c",
            "timestamp": "2026-07-06T12:34:00.000Z"
          },
          "witnessed_at": "2026-07-06T12:35:00.000Z",
          "signature": {
            "algorithm": "ed25519",
            "key_id": "did:web:witness-alpha.trust.example#witness-key-1",
            "value": "HNafqmtZIbXfL9SttdNhLD3CievyJpC2ESGQuUP9tgHdirUuCT+035qrpZQ1ntn3wqGSIFcZ4dO4QuVBD03kDw=="
          }
        },
        {
          "cosignature_version": "acdp-cosig/1",
          "witness_id": "did:key:z6Mki11Bt3TszrQcX7c1GuaNUc3gFh4XLWjCQWXrRis9QQeH",
          "witnessed_checkpoint": {
            "log_id": "did:web:registry-a.playground.local/log/receipts",
            "tree_size": 6,
            "root_hash": "sha256:d93fc06ae8e2dc9b3ea7c24060d3d9cfea9720eebc1aef1f06a9ae74de9c592c",
            "timestamp": "2026-07-06T12:34:00.000Z"
          },
          "witnessed_at": "2026-07-06T12:33:00.000Z",
          "signature": {
            "algorithm": "ed25519",
            "key_id": "did:key:z6Mki11Bt3TszrQcX7c1GuaNUc3gFh4XLWjCQWXrRis9QQeH#witness-key-1",
            "value": "AUu46Es/5ROnOPrIxQk2K2zl6C8b7kTfUEWOHNL7qn2SRQOOvSrho+UKP3og98O9aAqRespv/iTv73eCQKavAg=="
          }
        }
      ]
    }
  }
};
